#!/bin/bash

TASKS="T2bw_x-025_mStop-100to475_mLSP-0to300_LeptonFilter T2bw_x-025_mStop-100to475_mLSP-0to375 T2bw_x-025_mStop-500to650_mLSP-150to300_LeptonFilter T2bw_x-025_mStop-500to80_mLSP-0to700 T2bw_x-050_mStop-100to475_mLSP-0to300_LeptonFilter T2bw_x-050_mStop-100to475_mLSP-0to375 T2bw_x-050_mStop-500to650_mLSP-150to300_LeptonFilter T2bw_x-050_mStop-500to80_mLSP-0to700 T2bw_x-075_mStop-100to475_mLSP-0to300_LeptonFilter T2bw_x-075_mStop-100to475_mLSP-0to375 T2bw_x-075_mStop-500to650_mLSP-150to300_LeptonFilter T2bw_x-075_mStop-500to80_mLSP-0to700 T2tt_mStop-150to350_mLSP-0to250 T2tt_mStop-150to475_mLSP-1 T2tt_mStop-375to475_mLSP-0to375 T2tt_mStop-500to650_mLSP-0to225 T2tt_mStop-500to650_mLSP-250to550 T2tt_mStop-500to800_mLSP-1 T2tt_mStop-675to800_mLSP-0to275 T2tt_mStop-675to800_mLSP-300to700"

for TASK in $TASKS
do
    NRESUBMIT=`cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 != 0) print}' | grep -v "Submitted\|Scheduled\|Running" | wc -l`
    if [[ $NRESUBMIT -gt 0 ]]
    then
        echo Resubmitting $NRESUBMIT jobs for $TASK ...
        LIST=`cat $TASK/status.tmp | grep -E "^[0-9]" | awk '{if ($5 != 0) print}' | grep -v "Submitted\|Scheduled\|Running" | awk '{print $1}' | tr '\n' ',' | sed 's/,$//g'`
        crab -forceResubmit $LIST -c $TASK > log.tmp
        cat log.tmp | grep "submitted" | tail -n1
        rm log.tmp
    else
        echo No job to resubmit for $TASK
    fi
    
done
